### ISSUE TITLE
github page主题无法加载

### ISSUE THREAD

**Issue by yaunsine** [yelog/hexo-theme-3-hexo#134]
大佬您好，我这个上传了`themes\3-hexo`文件夹，同时在`_config.yml`配置了`theme: 3-hexo`后无法加载主题

```
/usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/theme.rb:84:in `rescue in gemspec': The 3-hexo theme could not be found. (Jekyll::Errors::MissingDependencyException)
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/theme.rb:81:in `gemspec'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/theme.rb:19:in `root'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/theme.rb:12:in `initialize'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:439:in `new'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:439:in `configure_theme'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:55:in `config='
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:23:in `initialize'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/commands/build.rb:30:in `new'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/commands/build.rb:30:in `process'
	from /usr/local/bundle/gems/github-pages-228/bin/github-pages:70:in `block (3 levels) in <top (required)>'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /usr/local/bundle/gems/github-pages-228/bin/github-pages:6:in `<top (required)>'
	from /usr/local/bundle/bin/github-pages:23:in `load'
	from /usr/local/bundle/bin/github-pages:23:in `<main>'
/usr/local/lib/ruby/2.7.0/rubygems/dependency.rb:3[11](https://github.com/yaunsine/yaunsine.github.io/actions/runs/4464703405/jobs/7841092665#step:4:12):in `to_specs': Could not find 'themes/anatolo' (>= 0) among 146 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/github/home/.gem/ruby/2.7.0:/usr/local/lib/ruby/gems/2.7.0:/usr/local/bundle', execute `gem env` for more information
	from /usr/local/lib/ruby/2.7.0/rubygems/dependency.rb:323:in `to_spec'
	from /usr/local/lib/ruby/2.7.0/rubygems/specification.rb:986:in `find_by_name'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/theme.rb:82:in `gemspec'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/theme.rb:19:in `root'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/theme.rb:[12](https://github.com/yaunsine/yaunsine.github.io/actions/runs/4464703405/jobs/7841092665#step:4:13):in `initialize'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:439:in `new'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:439:in `configure_theme'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:55:in `config='
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:23:in `initialize'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/commands/build.rb:30:in `new'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/commands/build.rb:30:in `process'
	from /usr/local/bundle/gems/github-pages-228/bin/github-pages:70:in `block (3 levels) in <top (required)>'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:[19](https://github.com/yaunsine/yaunsine.github.io/actions/runs/4464703405/jobs/7841092665#step:4:20):in `program'
	from /usr/local/bundle/gems/github-pages-[22](https://github.com/yaunsine/yaunsine.github.io/actions/runs/4464703405/jobs/7841092665#step:4:23)8/bin/github-pages:6:in `<top (required)>'
	from /usr/local/bundle/bin/github-pages:[23](https://github.com/yaunsine/yaunsine.github.io/actions/runs/4464703405/jobs/7841092665#step:4:24):in `load'
	from /usr/local/bundle/bin/github-pages:23:in `<main>'
  Logging at level: debug
```

**Comment by yaunsine** [comment]
本地运行是没有问题的

**Comment by yelog** [comment]
Due to an extended period of time, this issue is being closed. If you have any further questions or concerns, please feel free to submit them again.
