### ISSUE TITLE
请问是对hexo有版本要求吗?

### ISSUE THREAD

**Issue by amlove2** [yelog/hexo-theme-3-hexo#2]
C:\Users\kenxu\Desktop\amlove\cn\blog>hexo g > 1.txt
Unhandled rejection ReferenceError: C:\Users\kenxu\Desktop\amlove\cn\blog\themes
\3-hexo\layout\post.ejs:15
    13| <div class="post">
    14|     <div class="pjax">
 >> 15|         <%- partial('_partial/article', {post: page, index: false}) %>
    16|     </div>
    17|     <div class="copyright">
    18|         <%- partial('_partial/copyright')%>

C:\Users\kenxu\Desktop\amlove\cn\blog\themes\3-hexo\layout\_partial\article.ejs:
7
    5|       <% } %>
    6|       <%if(theme.word_count){%>
 >> 7|       <span>字数:<%=wordcount(post.content) %></span>
    8|       <%}%>
    9|       <%if(theme.visit_counter && theme.visit_counter.on && theme.visit_c
ounter.page_visit) {%>
    10|         <span id="busuanzi_container_page_pv">

wordcount is not defined
    at eval (eval at <anonymous> (C:\Users\kenxu\Desktop\amlove\cn\blog\node_mod
ules\ejs\lib\ejs.js:242:14), <anonymous>:30:646)
    at eval (eval at <anonymous> (C:\Users\kenxu\Desktop\amlove\cn\blog\node_mod
ules\ejs\lib\ejs.js:242:14), <anonymous>:30:3096)
    at C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\ejs\lib\ejs.js:255:15
    at _compiledSync (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\hexo\li
b\theme\view.js:122:20)
    at View.renderSync (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\hexo\
lib\theme\view.js:50:21)
    at Object.partial (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\hexo\l
ib\plugins\helper\partial.js:42:17)
    at Object.wrapper (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\lodash
\lodash.js:4968:19)
    at eval (eval at <anonymous> (C:\Users\kenxu\Desktop\amlove\cn\blog\node_mod
ules\ejs\lib\ejs.js:242:14), <anonymous>:30:423)
    at eval (eval at <anonymous> (C:\Users\kenxu\Desktop\amlove\cn\blog\node_mod
ules\ejs\lib\ejs.js:242:14), <anonymous>:30:876)
    at C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\ejs\lib\ejs.js:255:15
    at _compiled (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\hexo\lib\th
eme\view.js:127:30)
    at View.render (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\hexo\lib\
theme\view.js:29:15)
    at C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\hexo\lib\hexo\index.js
:387:25
    at tryCatcher (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\bluebird\j
s\release\util.js:16:23)
    at C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\bluebird\js\release\me
thod.js:15:34
    at RouteStream._read (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\hex
o\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:348:10)
    at resume_ (_stream_readable.js:737:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Unhandled rejection ReferenceError: C:\Users\kenxu\Desktop\amlove\cn\blog\themes
\3-hexo\layout\index.ejs:15
    13| <div class="post">
    14|     <div class="pjax">
 >> 15|         <%- partial('_partial/index') %>
    16|     </div>
    17|     <div class="copyright">
    18|         <%- partial('_partial/copyright')%>

C:\Users\kenxu\Desktop\amlove\cn\blog\themes\3-hexo\layout\_partial\index.ejs:46

    44|     <h2 id="关于叶落阁">关于叶落阁</h2>
    45|     <p><strong>叶落阁</strong>是阿杰（杨玉杰）的个人站。</p>
 >> 46|     <p>到目前为止已经写了<code><%=site.posts.length%></code>篇文章<%if(t
heme.word_count){%>， 共<code><%=totalcount(site)%></code>字</p><%}%>
    47|     <%if(theme.visit_counter && theme.visit_counter.on && theme.visit_co
unter.site_visit) {%>
    48|     <span id="busuanzi_container_site_uv">本站访问人数：<code><span id="
busuanzi_value_site_uv"></span></code>人次</span>
    49|     <span id="busuanzi_container_site_pv">， 访问量：<code><span id="bus
uanzi_value_site_pv"></span></code>次</span>

totalcount is not defined
    at eval (eval at <anonymous> (C:\Users\kenxu\Desktop\amlove\cn\blog\node_mod
ules\ejs\lib\ejs.js:242:14), <anonymous>:30:1765)
    at eval (eval at <anonymous> (C:\Users\kenxu\Desktop\amlove\cn\blog\node_mod
ules\ejs\lib\ejs.js:242:14), <anonymous>:30:3053)
    at C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\ejs\lib\ejs.js:255:15
    at _compiledSync (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\hexo\li
b\theme\view.js:122:20)
    at View.renderSync (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\hexo\
lib\theme\view.js:50:21)
    at Object.partial (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\hexo\l
ib\plugins\helper\partial.js:42:17)
    at Object.wrapper (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\lodash
\lodash.js:4968:19)
    at eval (eval at <anonymous> (C:\Users\kenxu\Desktop\amlove\cn\blog\node_mod
ules\ejs\lib\ejs.js:242:14), <anonymous>:30:430)
    at eval (eval at <anonymous> (C:\Users\kenxu\Desktop\amlove\cn\blog\node_mod
ules\ejs\lib\ejs.js:242:14), <anonymous>:30:851)
    at C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\ejs\lib\ejs.js:255:15
    at _compiled (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\hexo\lib\th
eme\view.js:127:30)
    at View.render (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\hexo\lib\
theme\view.js:29:15)
    at C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\hexo\lib\hexo\index.js
:387:25
    at tryCatcher (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\bluebird\j
s\release\util.js:16:23)
    at C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\bluebird\js\release\me
thod.js:15:34
    at RouteStream._read (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\hex
o\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:348:10)
    at resume_ (_stream_readable.js:737:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Unhandled rejection ReferenceError: C:\Users\kenxu\Desktop\amlove\cn\blog\themes
\3-hexo\layout\index.ejs:15
    13| <div class="post">
    14|     <div class="pjax">
 >> 15|         <%- partial('_partial/index') %>
    16|     </div>
    17|     <div class="copyright">
    18|         <%- partial('_partial/copyright')%>

C:\Users\kenxu\Desktop\amlove\cn\blog\themes\3-hexo\layout\_partial\index.ejs:46

    44|     <h2 id="关于叶落阁">关于叶落阁</h2>
    45|     <p><strong>叶落阁</strong>是阿杰（杨玉杰）的个人站。</p>
 >> 46|     <p>到目前为止已经写了<code><%=site.posts.length%></code>篇文章<%if(t
heme.word_count){%>， 共<code><%=totalcount(site)%></code>字</p><%}%>
    47|     <%if(theme.visit_counter && theme.visit_counter.on && theme.visit_co
unter.site_visit) {%>
    48|     <span id="busuanzi_container_site_uv">本站访问人数：<code><span id="
busuanzi_value_site_uv"></span></code>人次</span>
    49|     <span id="busuanzi_container_site_pv">， 访问量：<code><span id="bus
uanzi_value_site_pv"></span></code>次</span>

totalcount is not defined
    at eval (eval at <anonymous> (C:\Users\kenxu\Desktop\amlove\cn\blog\node_mod
ules\ejs\lib\ejs.js:242:14), <anonymous>:30:1765)
    at eval (eval at <anonymous> (C:\Users\kenxu\Desktop\amlove\cn\blog\node_mod
ules\ejs\lib\ejs.js:242:14), <anonymous>:30:3053)
    at C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\ejs\lib\ejs.js:255:15
    at _compiledSync (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\hexo\li
b\theme\view.js:122:20)
    at View.renderSync (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\hexo\
lib\theme\view.js:50:21)
    at Object.partial (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\hexo\l
ib\plugins\helper\partial.js:42:17)
    at Object.wrapper (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\lodash
\lodash.js:4968:19)
    at eval (eval at <anonymous> (C:\Users\kenxu\Desktop\amlove\cn\blog\node_mod
ules\ejs\lib\ejs.js:242:14), <anonymous>:30:430)
    at eval (eval at <anonymous> (C:\Users\kenxu\Desktop\amlove\cn\blog\node_mod
ules\ejs\lib\ejs.js:242:14), <anonymous>:30:851)
    at C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\ejs\lib\ejs.js:255:15
    at _compiled (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\hexo\lib\th
eme\view.js:127:30)
    at View.render (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\hexo\lib\
theme\view.js:29:15)
    at C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\hexo\lib\hexo\index.js
:387:25
    at tryCatcher (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\bluebird\j
s\release\util.js:16:23)
    at C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\bluebird\js\release\me
thod.js:15:34
    at RouteStream._read (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\hex
o\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:348:10)
    at resume_ (_stream_readable.js:737:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Unhandled rejection ReferenceError: C:\Users\kenxu\Desktop\amlove\cn\blog\themes
\3-hexo\layout\index.ejs:15
    13| <div class="post">
    14|     <div class="pjax">
 >> 15|         <%- partial('_partial/index') %>
    16|     </div>
    17|     <div class="copyright">
    18|         <%- partial('_partial/copyright')%>

C:\Users\kenxu\Desktop\amlove\cn\blog\themes\3-hexo\layout\_partial\index.ejs:46

    44|     <h2 id="关于叶落阁">关于叶落阁</h2>
    45|     <p><strong>叶落阁</strong>是阿杰（杨玉杰）的个人站。</p>
 >> 46|     <p>到目前为止已经写了<code><%=site.posts.length%></code>篇文章<%if(t
heme.word_count){%>， 共<code><%=totalcount(site)%></code>字</p><%}%>
    47|     <%if(theme.visit_counter && theme.visit_counter.on && theme.visit_co
unter.site_visit) {%>
    48|     <span id="busuanzi_container_site_uv">本站访问人数：<code><span id="
busuanzi_value_site_uv"></span></code>人次</span>
    49|     <span id="busuanzi_container_site_pv">， 访问量：<code><span id="bus
uanzi_value_site_pv"></span></code>次</span>

totalcount is not defined
    at eval (eval at <anonymous> (C:\Users\kenxu\Desktop\amlove\cn\blog\node_mod
ules\ejs\lib\ejs.js:242:14), <anonymous>:30:1765)
    at eval (eval at <anonymous> (C:\Users\kenxu\Desktop\amlove\cn\blog\node_mod
ules\ejs\lib\ejs.js:242:14), <anonymous>:30:3053)
    at C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\ejs\lib\ejs.js:255:15
    at _compiledSync (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\hexo\li
b\theme\view.js:122:20)
    at View.renderSync (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\hexo\
lib\theme\view.js:50:21)
    at Object.partial (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\hexo\l
ib\plugins\helper\partial.js:42:17)
    at Object.wrapper (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\lodash
\lodash.js:4968:19)
    at eval (eval at <anonymous> (C:\Users\kenxu\Desktop\amlove\cn\blog\node_mod
ules\ejs\lib\ejs.js:242:14), <anonymous>:30:430)
    at eval (eval at <anonymous> (C:\Users\kenxu\Desktop\amlove\cn\blog\node_mod
ules\ejs\lib\ejs.js:242:14), <anonymous>:30:851)
    at C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\ejs\lib\ejs.js:255:15
    at _compiled (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\hexo\lib\th
eme\view.js:127:30)
    at View.render (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\hexo\lib\
theme\view.js:29:15)
    at C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\hexo\lib\hexo\index.js
:387:25
    at tryCatcher (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\bluebird\j
s\release\util.js:16:23)
    at C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\bluebird\js\release\me
thod.js:15:34
    at RouteStream._read (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\hex
o\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:348:10)
    at resume_ (_stream_readable.js:737:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Unhandled rejection ReferenceError: C:\Users\kenxu\Desktop\amlove\cn\blog\themes
\3-hexo\layout\index.ejs:15
    13| <div class="post">
    14|     <div class="pjax">
 >> 15|         <%- partial('_partial/index') %>
    16|     </div>
    17|     <div class="copyright">
    18|         <%- partial('_partial/copyright')%>

C:\Users\kenxu\Desktop\amlove\cn\blog\themes\3-hexo\layout\_partial\index.ejs:46

    44|     <h2 id="关于叶落阁">关于叶落阁</h2>
    45|     <p><strong>叶落阁</strong>是阿杰（杨玉杰）的个人站。</p>
 >> 46|     <p>到目前为止已经写了<code><%=site.posts.length%></code>篇文章<%if(t
heme.word_count){%>， 共<code><%=totalcount(site)%></code>字</p><%}%>
    47|     <%if(theme.visit_counter && theme.visit_counter.on && theme.visit_co
unter.site_visit) {%>
    48|     <span id="busuanzi_container_site_uv">本站访问人数：<code><span id="
busuanzi_value_site_uv"></span></code>人次</span>
    49|     <span id="busuanzi_container_site_pv">， 访问量：<code><span id="bus
uanzi_value_site_pv"></span></code>次</span>

totalcount is not defined
    at eval (eval at <anonymous> (C:\Users\kenxu\Desktop\amlove\cn\blog\node_mod
ules\ejs\lib\ejs.js:242:14), <anonymous>:30:1765)
    at eval (eval at <anonymous> (C:\Users\kenxu\Desktop\amlove\cn\blog\node_mod
ules\ejs\lib\ejs.js:242:14), <anonymous>:30:3053)
    at C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\ejs\lib\ejs.js:255:15
    at _compiledSync (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\hexo\li
b\theme\view.js:122:20)
    at View.renderSync (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\hexo\
lib\theme\view.js:50:21)
    at Object.partial (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\hexo\l
ib\plugins\helper\partial.js:42:17)
    at Object.wrapper (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\lodash
\lodash.js:4968:19)
    at eval (eval at <anonymous> (C:\Users\kenxu\Desktop\amlove\cn\blog\node_mod
ules\ejs\lib\ejs.js:242:14), <anonymous>:30:430)
    at eval (eval at <anonymous> (C:\Users\kenxu\Desktop\amlove\cn\blog\node_mod
ules\ejs\lib\ejs.js:242:14), <anonymous>:30:851)
    at C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\ejs\lib\ejs.js:255:15
    at _compiled (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\hexo\lib\th
eme\view.js:127:30)
    at View.render (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\hexo\lib\
theme\view.js:29:15)
    at C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\hexo\lib\hexo\index.js
:387:25
    at tryCatcher (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\bluebird\j
s\release\util.js:16:23)
    at C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\bluebird\js\release\me
thod.js:15:34
    at RouteStream._read (C:\Users\kenxu\Desktop\amlove\cn\blog\node_modules\hex
o\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:348:10)
    at resume_ (_stream_readable.js:737:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by amlove2** [comment]
插件未装

**Comment by yelog** [comment]
谢谢提醒, 配置文件中已经修改为 默认不启用字数统计功能, 不会报错了
